apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-ecosystem-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-ecosystem-java-app
  template:
    metadata:
      labels:
        app: ci-cd-ecosystem-java-app
    spec:
      containers:
        - name: demo-app
          image: taeothapelodikgang/ci-cd-ecosystem-java-app:39
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ci-cd-ecosystem-java-app-service
spec:
  selector:
    app: ci-cd-ecosystem-java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
