apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-ecosystem-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-ecosystem-java-app
  template:
    metadata:
      labels:
        app: ci-cd-ecosystem-java-app
    spec:
      containers:
        - name: ci-cd-ecosystem-java-app
          image: taeothapelodikgang/ci-cd-ecosystem-java-app:third
          ports:
            - containerPort: 7080
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-ecosystem-java-app-service
spec:
  type: NodePort
  selector:
    app: ci-cd-ecosystem-java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7080
      nodePort: 30080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ci-cd-ecosystem-java-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: java-app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ci-cd-ecosystem-java-app-service
                port:
                  number: 80
